"use client"
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import {Menu} from '@headlessui/react';
import Link from 'next/link';
import {AdjustmentsHorizontalIcon, BellAlertIcon, BriefcaseIcon, ChevronDoubleDownIcon, ChevronDownIcon, ChevronRightIcon, ChevronUpIcon, Cog6ToothIcon, CursorArrowRippleIcon, ForwardIcon, HomeIcon, HomeModernIcon, SwatchIcon, TableCellsIcon, UserPlusIcon, VariableIcon} from '@heroicons/react/24/outline'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className='flex min-h-max flex-col'>
      <div className='flex flex-row justify-between'>
        <div className='flex '>
          <div className='p-1 mt-1 ml-1'>
            <Menu>
                {({open})=>(
                  <>
                    <Menu.Button className="group">
                      <div className='flex items-end'>
                        <p className='font-semibold text-sm group-hover:text-sky-400'>Actions</p>
                        {
                          open?
                            <>
                              <ChevronUpIcon className='ml-1 h-4 w-4 text-semibold text-black group-hover:text-sky-400'/>
                            </>
                            :
                            <>
                              <ChevronDownIcon className='ml-1 h-4 w-4 text-semibold text-black group-hover:text-sky-400'/>
                            </>
                        }
                      </div>
                    </Menu.Button>
                    <Menu.Items className="p-5 absolute z-10 bg-gray-50 mt-2 ml-2 rounded-xl shadow hover:shadow-lg">
                        <div className='flex flex-col'>
                          <Menu.Item>
                            <Link href="\" className="px-1 group hover:bg-gray-100 hover:rounded-xl hover:shadow py-1 flex flex-row justify-start items-center">
                              <div className='flex justify-center items-center p-2 bg-gray-200 group-hover:bg-white mr-2 rounded-md'>
                                <BriefcaseIcon className='h-7 w-7 text-black group-hover:text-indigo-500'/>
                              </div>
                              <div>
                                  <p className='font-semibold'>Accueil</p>
                                  <p>Tableau de bord présentant les états et les informations clés</p>
                              </div>
                            </Link>
                          </Menu.Item>
                          <Menu.Item>
                            <Link href="\inscription" className="px-1 group hover:bg-gray-100 hover:rounded-xl hover:shadow py-1 flex flex-row justify-start items-center">
                              <div className='flex justify-center items-center p-2 bg-gray-200 group-hover:bg-white mr-2 rounded-md'>
                                <UserPlusIcon className='h-7 w-7 text-black group-hover:text-green-500'/>
                              </div>
                              <div>
                                  <p className='font-semibold'>Inscription</p>
                                  <p>Créer votre compte et devenez acteur dans les processus de test</p>
                              </div>
                            </Link>
                          </Menu.Item>
                          <Menu.Item>
                            <Link href="\" className="px-1 group hover:bg-gray-100 hover:rounded-xl hover:shadow py-1 flex flex-row justify-start items-center">
                              <div className='flex justify-center items-center p-2 bg-gray-200 group-hover:bg-white mr-2 rounded-md'>
                                <CursorArrowRippleIcon className='h-7 w-7 text-black group-hover:text-sky-500'/>
                              </div>
                              <div>
                                  <p className='font-semibold'>Commandes</p>
                                  <p> Suivez les commandes de la création à la livraison</p>
                              </div>
                            </Link>
                          </Menu.Item>

                          
                        </div>
                    </Menu.Items>
                  </>
                )}
            </Menu>
          </div>
          <div className='p-1 mt-1 ml-1'>
            <div className='group'>
                <Link href="/" className='group-hover:text-sky-400 text-sm font-semibold'>Réglages</Link>
            </div>
          </div>
          <div className='p-1 mt-1 ml-1'>
            <div className='group'>
                <Link href="/" className='group-hover:text-sky-400 text-sm font-semibold'>A propos</Link>
            </div>
          </div>
          <div className='p-1 mt-1 ml-1'>
            <div className='group'>
                <Link href="/" className='group-hover:text-sky-400 text-sm font-semibold'>Aide</Link>
            </div>
          </div>
          <div className='p-1 mt-1 ml-1'>
            <div className='group'>
              <Menu>
                  {({open})=>(
                    <>
                      <Menu.Button className="group">
                        <div className='flex items-end'>
                          <p className='font-semibold text-sm group-hover:text-sky-400'>Utiles</p>
                          {
                            open?
                              <>
                                <ChevronUpIcon className='ml-1 h-4 w-4 text-semibold text-black group-hover:text-sky-400'/>
                              </>
                              :
                              <>
                                <ChevronDownIcon className='ml-1 h-4 w-4 text-semibold text-black group-hover:text-sky-400'/>
                              </>
                          }
                        </div>
                      </Menu.Button>
                      <Menu.Items className="p-5 absolute z-10 bg-gray-50 mt-2 ml-2 rounded-xl shadow hover:shadow-lg">
                          <div className='flex flex-col'>
                            <Menu.Item>
                              <Link href="\" className="px-1 group hover:bg-gray-100 hover:rounded-xl hover:shadow py-1 flex flex-row justify-start items-center">
                                <div className='flex justify-center items-center p-2 bg-gray-200 group-hover:bg-white mr-2 rounded-md'>
                                  <TableCellsIcon className='h-7 w-7 text-black group-hover:text-indigo-500'/>
                                </div>
                                <div>
                                    <p className='font-semibold'>Normes</p>
                                    <p>La liste des normes enregistrées dans le système (export Pdf)</p>
                                </div>
                              </Link>
                            </Menu.Item>
                            <Menu.Item>
                              <Link href="\" className="px-1 group hover:bg-gray-100 hover:rounded-xl hover:shadow py-1 flex flex-row justify-start items-center">
                                <div className='flex justify-center items-center p-2 bg-gray-200 group-hover:bg-white mr-2 rounded-md'>
                                  <VariableIcon className='h-7 w-7 text-black group-hover:text-green-500'/>
                                </div>
                                <div>
                                    <p className='font-semibold'>Essais</p>
                                    <p> La liste des essais enregistrés dans le système</p>
                                </div>
                              </Link>
                            </Menu.Item>
                            <Menu.Item>
                              <Link href="\" className="px-1 group hover:bg-gray-100 hover:rounded-xl hover:shadow py-1 flex flex-row justify-start items-center">
                                <div className='flex justify-center items-center p-2 bg-gray-200 group-hover:bg-white mr-2 rounded-md'>
                                  <SwatchIcon className='h-7 w-7 text-black group-hover:text-sky-500'/>
                                </div>
                                <div>
                                    <p className='font-semibold'>Matériaux</p>
                                    <p> La liste des matériaux enregistrées dans le système</p>
                                </div>
                              </Link>
                            </Menu.Item>

                            
                          </div>
                      </Menu.Items>
                    </>
                  )}
              </Menu>
            </div>
          </div>
          <div className='p-1 mt-1 ml-1'>
            <div className='group'>
                <Link href="/" className='group-hover:text-sky-400 text-sm font-semibold'>
                  <span className='p-1 bg-red-500 text-white ring-1 shadow-sm rounded-md'>Version d'essai</span>
                </Link>
            </div>
          </div>
        </div>
        <div className='mt-3 me-2'>
          <BellAlertIcon className='text-black h-5 w-5'/>
        </div>
      </div>
      {children}
    </div>

  )
}